name: release

on: workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: "Install Python 3.10"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Build
        run: python -m pip install build

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build sdist and wheel
        run: python -m build . -o dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Sdist and Wheel
          path: dist/
